In [4]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

In [7]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived'])

In [9]:
df.dropna(inplace=True)

In [11]:
df.shape

(714, 3)

In [13]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [14]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),
                                                 df['Survived'],
                                                 random_state=42,
                                                 train_size=0.2)

In [15]:
X_train.head()

      Age     Fare
762  20.0   7.2292
754  48.0  65.0000
701  35.0  26.2875
110  47.0  52.0000
302  19.0   0.0000

In [16]:
Dclf = DecisionTreeClassifier()

In [17]:
Dclf.fit(X_train,y_train)
y_pred = Dclf.predict(X_test)

In [18]:
accuracy_score(y_test,y_pred)

0.6118881118881119